#ifndef MATHLIB_IMPLEMENTATION_GEOMETRY_2D_INTERSECT_HPP
#define MATHLIB_IMPLEMENTATION_GEOMETRY_2D_INTERSECT_HPP

#include "Shapes.hpp"

namespace Math::Geometry2D
{
}

#endif //MATHLIB_IMPLEMENTATION_GEOMETRY_2D_INTERSECT_HPP
