#ifndef MATHLIB_IMPLEMENTATION_GEOMETRY_2D_TRANSFORM_HPP
#define MATHLIB_IMPLEMENTATION_GEOMETRY_2D_TRANSFORM_HPP

#include "Shapes.hpp"

namespace Math::Geometry2D
{
}

#endif //MATHLIB_IMPLEMENTATION_GEOMETRY_2D_TRANSFORM_HPP
